<img src="https://i.esdrop.com/d/7o0dj05m8rnz/JNGCMedl18.png" width="45%">

# Logistic Regression

---

## Import Packages
- Visual Python: Data Analysis > Import

In [1]:
# Visual Python: Data Analysis > Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

## 1 Logistic Regression

In [2]:
# Visual Python: Data Analysis > File
df = pd.read_csv('./data/12_1_로지스틱회귀분석.csv')
df

     성별  직급   외관  편의성  유용성  만족감
0    남자  사원  4.0  3.0  3.0  3.0
1    남자  사원  5.0  3.0  1.0  5.0
2    남자  사원  5.0  3.0  3.0  5.0
3    남자  사원  5.0  4.0  3.0  3.0
4    남자  사원  5.0  3.0  4.0  5.0
..   ..  ..  ...  ...  ...  ...
320  남자  과장  1.0  1.0  1.0  2.0
321  남자  과장  5.0  4.0  3.0  3.0
322  여자  과장  1.0  3.0  3.0  3.0
323  여자  사원  5.0  4.0  3.0  5.0
324  남자  사원  1.0  1.0  1.0  2.0

[325 rows x 6 columns]

In [3]:
# Visual Python: Logistic Regression
vp_df = df.dropna().copy()
vp_df['성별'+'_EL'] = pd.Categorical(vp_df['성별']).codes

# Logistic regression
from IPython.display import display
import statsmodels.formula.api as smf
_model  = smf.logit('성별_EL ~ 외관 + 편의성 + 유용성 + 만족감', vp_df)
_result = _model.fit()
print(_result.summary())

# Multi-collinearity statistics
from statsmodels.stats.outliers_influence import variance_inflation_factor
_dfr = pd.DataFrame(_result.summary().tables[1].data[1:],columns=_result.summary().tables[1].data[0]).set_index('')
_dfr['Odds'] = np.exp(_result.params)
_dfr['Lower(Odds)'] = np.exp(_result.conf_int()[0])
_dfr['Upper(Odds)'] = np.exp(_result.conf_int()[1])
for i, col in enumerate(_model.exog_names[1:]):
    _vif = variance_inflation_factor(_model.exog, i+1)
    _dfr.loc[col,'Tolerance'] = 1/_vif
    _dfr.loc[col,'VIF'] = _vif
display(_dfr)

Optimization terminated successfully.
         Current function value: 0.633501
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  성별_EL   No. Observations:                  325
Model:                          Logit   Df Residuals:                      320
Method:                           MLE   Df Model:                            4
Date:                Sat, 11 May 2024   Pseudo R-squ.:                 0.03559
Time:                        15:29:42   Log-Likelihood:                -205.89
converged:                       True   LL-Null:                       -213.48
Covariance Type:            nonrobust   LLR p-value:                  0.004315
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -2.6440      0.709     -3.729      0.000      -4.034      -1.254
외관            -0.0078      0.106     -0.074      0.941      -0.215       0.199
편의성            0.2931      0.140      2.099      0.036       0.019       0.567
유용성           -0.1015      0.154     -0.657      0.511      -0.404       0.201
만족감            0.4046      0.151      2.675      0.007       0.108       0.701
==============================================================================

,coef,std err,z,P>|z|,[0.025,0.975],Odds,Lower(Odds),Upper(Odds),Tolerance,VIF
,,,,,,,,,,,
Intercept,-2.6440,0.709,-3.729,0.000,-4.034,-1.254,0.071074,0.017705,0.285312,NaN,NaN
외관,-0.0078,0.106,-0.074,0.941,-0.215,0.199,0.992196,0.806534,1.220596,0.923684,1.082622
편의성,0.2931,0.140,2.099,0.036,0.019,0.567,1.340567,1.019643,1.762501,0.920790,1.086024
유용성,-0.1015,0.154,-0.657,0.511,-0.404,0.201,0.903518,0.667604,1.222798,0.864443,1.156814
만족감,0.4046,0.151,2.675,0.007,0.108,0.701,1.498759,1.114171,2.016100,0.807449,1.238469

---

In [4]:
# End of file